### ISSUE TITLE
JAR does not function properly when using MultiEgg.

### ISSUE THREAD

**Issue by RealTriassic** [RealTriassic/Ptero-VM-JAR#1]
## What's the Issue?
When running the jarfile in a hosting service that uses ExoticalCat's MultiEgg for Pterodactyl, the server startup fails completely when using the OpenJ9 version of the egg. I assume this may be an issue with running the jar under OpenJ9 overall, though I am unconvinced.

## Extra Information
When attempting to run this in a hosting service called FalixNodes.net, the server boots, but downloading `installer.sh` fails completely, this is possibly caused by the hosting service blocking the download link, if that is the case, the workaround is simple and it involves possibly changing the download link for the file.

## 

##

**Comment by RealTriassic** [comment]
## Workaround
Download the `installer.sh` file to load from, you can download it manually [here](https://raw.githubusercontent.com/afnan007a/Ptero-vm/main/installer.sh), once you have downloaded it, go ahead and and upload it to the files of your server and the Jarfile should load from it instead of trying to download the file from source.

**Comment by RealTriassic** [comment]
A commit has been pushed to ease the issue of running the Jarfile on FalixNodes, atleast as much as we can, Installer.sh will still fail to download it's dependencies, but that has to be fixed by the original Ptero-VM developers.

**Comment by FatGrizzly** [comment]
To combat this, we can possibly try downloading installer.sh via various proxies/cdn's(trying to reduce user interaction)

I have listed a few proxies/cdn's.
https://ghcdn.rawgit.org/afnan007a/Ptero-vm/master/installer.sh
https://cdn.jsdelivr.net/gh/afnan007a/Ptero-vm@main/installer.sh
https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/afnan007a/Ptero-vm/main/installer.sh
https://raw.fastgit.org/afnan007a/Ptero-vm/main/installer.sh
https://github.123vip.workers.dev/-----https://raw.githubusercontent.com/afnan007a/Ptero-vm/main/installer.sh

**Comment by RealTriassic** [comment]
This seems to no longer occur.
